services:
  - type: web
    name: kino-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    pythonVersion: 3.11
